export interface Content{
    id: number,
    title: string,
    description: string,
    creator: string,
    imgURL?: string,
    type?: string,
    tags?: string[],
    address?: String,
    email?: string,
    phone?: string,
    url?: string,
    website?: string,
    status?: boolean,
}